sudo: false
language: python
python:
  - 3.6

# install steps MUST succeed or will immediately halt the build
install:
  - pip install flake8
  - pip install -r requirements.txt

# script steps, if erroring, will fail the build but not stop the build process
# this is handy because we want to know that linting is broken, but it shouldn't
# stop us from testing/linting/compiling other things as well
script:
  - flake8 --statistics --show-source --disable-noqa
